server:
	ip-address: 127.12.12.12@5335
	port: 5335
	do-ip4: yes
	do-ip6: no
	username: nsd
	hide-version: yes
	hide-identity: yes

	# Used only to keep the NSD process running in the foreground; prevent it from daemonizing
	debug-mode: yes


zone:
	name: "."
	zonefile: "/var/nsd/root.zone"

	# 192.0.32.132 - xfr.lax.dns.icann.org
	# 192.0.47.132 - xfr.cjr.dns.icann.org

	allow-notify: 192.0.32.132 NOKEY
	allow-notify: 192.0.47.132 NOKEY

	request-xfr: 192.0.32.132 NOKEY
	request-xfr: 192.0.47.132 NOKEY


remote-control:
	control-enable: no
